#
# Copyright (c) 2001-2018 Primeton Technologies, Ltd.
# All rights reserved.
#
# author: ZhongWen Li (mailto:lizw@primeton.com)
#

FROM sonatype/nexus3:3.5.0

LABEL maintainer="lizw@primeton.com" \
    provider="Primeton Technologies, Ltd."