version: '3'
services:
  mysql:
    image: harbor.registry.com/primeton/mysql:5.6
    volumes:
      - "/data/mysql:/var/lib/mysql"
    ports:
      - 3306:3306
    env_file:
      - ./conf/mysql/env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
      labels:
        provider: "Primeton"
        category: "DevOPS"
      placement:
        constraints: [node.role != manager]
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 256M

  devops:
    image: harbor.registry.com/primeton/devops:5.0
    volumes:
      - "/data/devops/work:/tomcat/apps_config/ROOT/work_temp"
      # - "/data/devops/license/primetonlicense.xml:/tomcat/apps_config/ROOT/license/primetonlicense.xml"
    ports:
      - 8080:8080
    env_file:
      - conf/devops/env
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
      labels:
        provider: "Primeton"
        category: "DevOPS"
      placement:
        constraints: [node.role != manager]
      resources:
        limits:
          memory: 8192M
        reservations:
          memory: 1024M

  sonar:
    image: harbor.registry.com/primeton/sonar:6.3
    volumes:
      - "/data/sonar:/opt/sonarqube/data"
    ports:
      - 9000:9000
    env_file:
      - conf/sonar/env
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
      labels:
        provider: "Primeton"
        category: "DevOPS"
      placement:
        constraints: [node.role != manager]
      resources:
        limits:
          memory: 8192M
        reservations:
          memory: 4096M

  nexus:
    image: harbor.registry.com/primeton/nexus:3.5.0
    volumes:
      - "/data/nexus:/nexus-data"
    ports:
      - 8081:8081
    env_file:
      - conf/nexus/env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
      labels:
        provider: "Primeton"
        category: "DevOPS"
      placement:
        constraints: [node.role != manager]
      resources:
        limits:
          memory: 8192M
        reservations:
          memory: 1024M

  jenkins:
    image: harbor.registry.com/primeton/jenkins:2
    volumes:
      - "/data/jenkins/workspace:/opt/work/workspace"
      - "/data/jenkins/m2:/root/.m2"
      - "/data/jenkins/m2:/home/jenkins/.m2"
    ports:
      - 8010:8080
    env_file:
      - conf/jenkins/env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
      labels:
        provider: "Primeton"
        category: "DevOPS"
      placement:
        constraints: [node.role != manager]
      resources:
        limits:
          memory: 8192M
        reservations:
          memory: 2048M

  gitlab:
    image: harbor.registry.com/primeton/gitlab:9.1.2
    volumes:
      - "/data/gitlab/config:/etc/gitlab"
      - "/data/gitlab/logs:/var/log/gitlab"
      - "/data/gitlab/data:/var/opt/gitlab"
    ports:
      - 443:443
      - 22:22
      - 80:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
      labels:
        provider: "Primeton"
        category: "DevOPS"
      placement:
        constraints: [node.role != manager]
      resources:
        limits:
          memory: 8192M
        reservations:
          memory: 2048M

  jira:
    image: harbor.registry.com/primeton/jira:7.3.1
    volumes:
      - "/data/jira/attachments:/opt/jirasoftware-home/data/attachments"
      - "/data/jira/log:/opt/jirasoftware-home/log"
      - "/data/jira/export:/opt/jirasoftware-home/export"
      - "/data/jira/caches:/opt/jirasoftware-home/caches"
    ports:
      - 8090:8090
    env_file:
      - conf/jira/env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
      labels:
        provider: "Primeton"
        category: "DevOPS"
      placement:
        constraints: [node.role != manager]
      resources:
        limits:
          memory: 8192M
        reservations:
          memory: 1024M
